iOS: Add `bundleId` override for use with different schemes/configurations.
SudoPlz/sp-react-native-in-app-updates pull request #148
Opened 2023-05-17 10:28 UTC by GunnarAK

2023-07-19 14:17 UTC, robbeman requested changes

2023-07-19 14:17 UTC, robbeman commented on src/types.ts
> +   * Bundle ID override
```suggestion
   * Bundle ID override (iOS only)
```

2024-01-29 21:46 UTC, SudoPlz approved these changes

2024-01-29 21:46 UTC, merged

2024-01-29 21:46 UTC, SudoPlz commented
Thank you 🎉